### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by char0n** [CodeScaleInc/django-brevisurl#25]
Hi @beld2107,

There is a pull request merged on master branch. Would you be so kind to release a new version, if and when you have time.

Thank you.

**Comment by beld2107** [comment]
I'll do it by Monday if that works for you

**Comment by char0n** [comment]
Cool, thanks.

On Thu, Oct 15, 2015 at 6:30 PM, Denis Bellavance <notifications@github.com>
wrote:

> I'll do it by Monday if that works for you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CodeScaleInc/django-brevisurl/issues/25#issuecomment-148446131>
> .
>



-- 

Vladimír Gorej | CodeScale s.r.o.
email: gorej@codescale.net
tel: +420 777 861 279, +421 948 023 011
web: http://www.codescale.net

**Comment by beld2107** [comment]
It's pushed!

**Comment by char0n** [comment]
Nice :)
